name: portfolio2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^0.3.9
  font_awesome_flutter: ^8.7.0
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/placelytics/
    - assets/pictile/
    - assets/thg/

  fonts:
    - family: Kontanter
      fonts:
        - asset: fonts/Kontanter.otf

    - family:  MyIcons
      fonts:
        - asset: fonts/MyIcons.ttf

    - family: Etna
      fonts:
        - asset: fonts/Etna.otf
    
    - family: Prime
      fonts:
        - asset: fonts/Prime-Regular.otf